version: '3'

services:
  app:
    build: ./app
    container_name: app
    volumes:
      - ./app:/usr/src/app
    # ports:
    #   - 5001:5000
    expose:
    #   - 8080
      - 5001
    environment:
      POSTGRES_USER: fatec
      POSTGRES_PASSWORD: fatec
      POSTGRES_DB: pi
      
  sonarqube:
    image: sonarqube
    container_name: sonarqubeR4u
    ports:
    - 9000:9000

  # nginx:
  #   build: ./nginx
  #   container_name: nginx
  #   ports:
  #   - 6001:6001
